<?php
include $_SERVER['DOCUMENT_ROOT'] . '/ELECTRONIC LIBRARY/PHP Actions/connections.php';
?>

<!DOCTYPE html>

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <link rel="icon" type="image/jpeg" href="../pics/logo.jpg">

  <title>??? | Book</title>
  
  <link rel="stylesheet" href="../css/book.css" />
  <link rel="stylesheet" href="../css/dark-book.css" />
  <script src="../javascript/book.js" defer></script>
</head>

<body>

<?php include $_SERVER['DOCUMENT_ROOT'] . '/ELECTRONIC LIBRARY/Navigation-bar.php'; ?>

<nav class="breadcrumb">
  <ol class="breadcrumb-list">

    <li class="breadcrumb-item">
      <a href="/Electronic Library/categories.php">Categories</a>
    </li>
    <li class="breadcrumb-item">
      <a href="/Electronic Library/Categories/science.php">Science</a>
    </li>

    <!-- current page – no link -->
      <li class="breadcrumb-item active"  aria-current="page">
          The Elegent Universe
      </li>
  </ol>  
</nav>


<main class="book-container">

  <div class="book-header">
  
    <div class="book-cover-wrapper">
      <img 
        src="../Pics/books/elegentuniverse.jpg"
        alt="The Elegent Universe" 
        class="book-cover"
      />
    </div>

    <div class="book-info">
      <h1 class="book-title">The Elegent Universe</h1>
      <p class="book-author">Brian Greene</p>
        
    <div class="meta-row">
      <span class="meta-item">1999</span>
  <span class="meta-item">464 pages</span>
  <span class="meta-item">English</span>
  <span class="meta-item rating">
    4.10 (165,611 ratings)
  </span>
</div>

        <div class="genres">
  <span class="genre-tag">Science</span>
  <span class="genre-tag">Physics</span>
</div>

        <div class="action-buttons">
          <button class="btn primary" onclick="window.open('../PDFs/elegentuniverse.pdf', '_blank')">Read Now</button>
          <button class="btn secondary">Add to Favorites</button>
          <button class="btn tertiary">Download PDF</button>
        </div>
        
      </div>
    </div>

    <section class="book-description">
  <h2>Description</h2>
  <p>
    Brian Greene, one of the world's leading string theorists, peels away the layers of mystery surrounding string theory to reveal a universe that consists of eleven dimensions, where the fabric of space tears and repairs itself, and all matter, from the smallest quarks to the most gargantuan supernovas, is generated by the vibrations of microscopically tiny loops of energy. 
    
    String theory, as it is often called, is the key to the Unified Field Theory that eluded Einstein for more than thirty years. Finally, the century-old antagonism between the large and the small (General Relativity and Quantum Theory) is resolved. String theory proclaims that all of the wondrous happenings in the universe, from the frantic dancing of subatomic quarks to the majestic swirling of heavenly galaxies, are reflections of one grand physical principle and manifestations of one single entity: microscopically tiny vibrating loops of energy, a billionth of a billionth the size of an atom. 
    
    In this book, Greene relates the scientific story and the human struggle behind twentieth-century physics' search for a theory of everything. Through the masterful use of metaphor and analogy, The Elegant Universe makes some of the most sophisticated concepts ever contemplated viscerally accessible and thoroughly entertaining, bringing us closer than ever to understanding how the universe works.
  </p>
</section>

  </section>

    <section class="book-details-section">
      <h2>Book Details</h2>
      <div class="details-grid">
        <div class="detail-item">
          <span class="label">Publisher</span>
          <span class="value">W. W. Norton & Company</span>
        </div>
        <div class="detail-item">
          <span class="label">ISBN</span>
          <span class="value">978-0-06-231500-7</span>
        </div>
        <div class="detail-item">
          <span class="label">Publication Date</span>
          <span class="value">February 1, 1999</span>
        </div>
        <div class="detail-item">
          <span class="label">File Size</span>
          <span class="value">7.2 MB (PDF)</span>
        </div>
        <div class="detail-item">
          <span class="label">Format</span>
          <span class="value">PDF, EPUB</span>
        </div>
      </div>
    </section>

</main>


</body>
</html>